name: ProNouns
version: '${version}'
main: net.lucypoulton.pronouns.paper.ProNounsPaper
api-version: 1.19
authors: [lucyydotp]
website: https://lucypoulton.net

# commands and permissions are defined at runtime
